import turtle
import colorama
import time
scene = turtle.Screen()
scene.bgcolor('SkyBlue')
evan = turtle.Turtle()
evan.shape("turtle")
evan.color("Red")
evan.penup()
evan.goto(-100,0)
evan.fillcolor("Red")
evan.pendown()
evan.begin_fill()
evan.goto(-100,50)
evan.goto(100,50)
evan.goto(100,0)
evan.goto(-100,0)
evan.end_fill()
evan.penup()
evan.goto(-100,50)
evan.fillcolor("Brown")
evan.pendown()
evan.begin_fill()
evan.goto(0,100)
evan.goto(100,50)
evan.goto(-100,50)
evan.end_fill()
evan.penup()
evan.goto(-40,0)
evan.fillcolor("Orange")
evan.pendown()
evan.begin_fill()
evan.goto(-40,30)
evan.goto(-20,30)
evan.goto(-20,0)
evan.goto(-40,0)
evan.end_fill()
evan.penup()
evan.goto(20,20)
evan.fillcolor("White")
evan.pendown()
evan.begin_fill()
evan.goto(20,40)
evan.goto(50,40)
evan.goto(50,20)
evan.goto(20,20)
evan.end_fill()
evan.hideturtle()
time.sleep(8)
